services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: paymentflow-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD:-Your_strong_Passw0rd!}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/PaymentFlow.Api/Dockerfile
    container_name: paymentflow-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=PaymentFlow;User Id=sa;Password=${SQL_SA_PASSWORD:-Your_strong_Passw0rd!};TrustServerCertificate=True"
      Jwt__Secret: ${JWT_SECRET:?Set JWT_SECRET in .env}
      Seed__DemoPassword: ${SEED_DEMO_PASSWORD:-Demo!Passw0rd1}
    ports:
      - "5080:8080"

volumes:
  sqlserver-data:
